version: "3"
services:
  # --- COLLECTOR ---
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "8888:8888" # Metrics endpoint
    depends_on:
      - jaeger
      - prometheus
      - loki

  # --- TRACES ---
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - QUERY_UI_CONFIG=/etc/jaeger/jaeger-ui.json
    volumes:
      - ./jaeger-ui.json:/etc/jaeger/jaeger-ui.json
    ports:
      - "16686:16686" # UI
      - "14250:14250"

  # --- METRICS ---
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # UI

  # --- LOGS ---
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

