receivers:
  otlp:
    protocols:
      grpc: # Port 4317 (For Backend/Go/Node)
      http: # Port 4318 (For Frontend/JS)

processors:
  batch: # Groups data to avoid saturation, vital in production
    timeout: 1s # 1s for fast data viewing in the demo

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889" # Exposes metrics for Prometheus to read
  
  otlp: # Sends traces to Jaeger
    endpoint: "jaeger:4317" 
    tls:
      insecure: true

   loki: # Sends logs to Loki
     endpoint: "http://loki:3100/loki/api/v1/push"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp] # To Jaeger
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus] # To Prometheus
     logs:
       receivers: [otlp]
       processors: [batch]
       exporters: [loki] # To Loki